import Head from "next/head";
import styles from "src/styles/Home.module.css";
import { Header } from "src/components/Header";
import { Posts as PostsComponent } from "src/components/Posts";

const Posts = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Posts Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <PostsComponent />
    </div>
  );
};

export default Posts;