import Head from 'next/head';
import styles from 'src/styles/Home.module.css';
import { Footer } from "src/components/Footer";
import { Main } from 'src/components/Main';
import { Header } from 'src/components/Header';

export default function About({
    doubleCount,
    isShow, 
    handleClick, 
    handleDisplay, 
    text, 
    array, 
    handleChange, 
    handleAdd
  }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <Header />
      <Main page="about" />

      {isShow ? <h1>{doubleCount}</h1> : null}

      <button onClick={handleClick}>カウント</button>
      <button onClick={handleDisplay}>{isShow ? "非表示" : "表示"}</button>

      <input type="text" value={text} onChange={handleChange} />
      <button onClick={handleAdd}>追加</button>
      <ul>
        {array.map(item => {
          return <li key={item}>{item}</li>
        })}
      </ul>
      
      <Footer />
    </div>
  );
}