import Head from 'next/head';
import styles from 'src/styles/Home.module.css';
import { Footer } from "src/components/Footer";
import { Main } from 'src/components/Main';
import { Header } from 'src/components/Header';
import { useCallback } from 'react';
import Link from "next/link";

export default function Home() {
  const foo = 1;

  const handleClick = useCallback((e) => {
    console.log(e.target.href);
    e.preventDefault();
    alert(foo);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Main page="index" />
      
      <Link href="/about">
        <a onClick={handleClick}>Button</a>
      </Link>

      <Footer />
    </div>
  );
}