import Head from "next/head";
import { Header } from "src/components/Header";

const Index = () => {
  return (
    <div className="text-center">
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <h1 className="text-3xl font-bold mt-20">Next.jsで学ぶReact</h1>
      <p className="text-xl mt-10">JSONPlaceholderのAPIを叩いてブログ開発</p>
    </div>
  );
};

export default Index;
